name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        run: |
          docker login --username k2on --password {{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/k2on/site:0.0.1
          docker push ghcr.io/k2on/site:0.0.1

